services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    volumes:
      - ./app:/app
      - shared-volume:/backup
    depends_on:
      - mssql
    env_file:
      - .env
    command: ["/usr/local/bin/wait-for-it.sh", "mssql:1433", "--", "python", "run.py"]

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
    # add /data at the end if getting permission error
      - db_data:/var/opt/mssql # Mount the db_data volume
      - shared-volume:/backup
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - TZ=Asia/Kathmandu
    ports:
      - "1433:1433"  # Expose the MSSQL port

volumes:
  db_data:
  shared-volume: